### ISSUE TITLE
GravityForms error handling doesn't work with plugin

### ISSUE THREAD

**Issue by admodiggity** [gravityplus/Gravity-Forms-Stripe#1]
If a required field is left blank, and the submit button pushed, there is no specific indication of what is wrong.

The plugin gives a "This form cannot process payments. Please contact site owner" error, with a spinning "working" indicator next to the submit button that never stops spinning.

![No error handling](http://www.adamrichardson.com/naomi-donation-fail.png)

**Comment by naomicbush** [comment]
Grab version 0.1.2.

commit [f2772af025](https://github.com/naomicbush/Gravity-Forms-Stripe/commit/f2772af0253c1363bddddd62a38da009deb965be) `Fix error handling`
