### ISSUE TITLE
Unable to add Credit Card field

### ISSUE THREAD

**Issue by jamesvandyke** [gravityplus/Gravity-Forms-Stripe#10]
I just installed the testing branch code to test subscriptions.

I'm unable to add a credit card field.

I created a new form and then attempted to add the credit card field.

I get this javascript error after clicking the "Credit Card" button in the Pricing Fields:

Uncaught SyntaxError: Unexpected token < 

It says the error is in the tw-sack.js file on line 1. I could trace the file to the Wordpress includes folder, but I'm not sure where to explore from there.

Let me know if you need more information or if I shouldn't be playing with the testing branch!

**Comment by naomicbush** [comment]
Hi @jamesvandyke, playing w/ the testing branch is good :)  I'll check this issue out.

What version of GF are you using? I haven't tested on 1.6.4 yet.

**Comment by pnommensen** [comment]
@naomicbush & @jamesvandyke  : Using Version 0.2-beta of the add-on with Version 1.6.4.2.1 of Gravity Forms I was able to add the credit card file into a new form with no such error.  I'm not sure if this is the testing branch?

**Comment by naomicbush** [comment]
@pnommensen yes, I sent you the version I pushed to the testing branch.

**Comment by pnommensen** [comment]
@naomicbush  Just took it for a test-run. It's brilliant! :D. Here's the form in case anyone wants to see: http://67.222.4.234/secure.rfahaiti.org/donate/ 

I see in the upcoming features you have listed receipt. Couldn't that just be done via gravity forms "Notification to User."

**Comment by jamesvandyke** [comment]
I'm using GF 1.6.4.2. and 0.2-beta of your plugin. I'm on WP 3.3.2 Multisite. 

I'm playing with it on our development site so it may just be a conflict with some code I've written. I'll try a plain vanilla install later today and see if I can duplicate it.

**Comment by naomicbush** [comment]
@jamesvandyke what's the verdict?

**Comment by jamesvandyke** [comment]
Sorry this took so long. Looks like it was an issue on my end. Seems to work fine on a basic install.

**Comment by diehendrick** [comment]
i'm using gf 1.6.2 developer version but, credi card field not show, i'm on WP 3.4.1

**Comment by naomicbush** [comment]
Hi, you need the latest version of Gravity Forms.
