### ISSUE TITLE
Test webhook error: 301 

### ISSUE THREAD

**Issue by pnommensen** [gravityplus/Gravity-Forms-Stripe#12]
Hello! Using the version you sent me via email a little while ago I'm getting a "Test webhook error: 301" in the stripe dashboard when I go to test the webhook. I assume this isn't a good thing yet the test payments still seem to be going through.

**Comment by naomicbush** [comment]
Hi @pnommensen :-) That 301 error is the HTTP status code Stripe is receiving back from your server which makes me think its an issue unrelated to the plugin. Sounds like you have some sort of 301 redirects set up for whatever server you're using.

**Comment by pnommensen** [comment]
Hmm, okay. When I go to
https://www.secure.rfahaiti.org/donate/?page=gf_stripe_listener  I'm seeing
the following errors:

_Warning_: Missing argument 2 for
Stripe_InvalidRequestError::__construct(), called in /home/admin/domains/
rfahaiti.org/private_html/secure/donate/wp-content/plugins/gravityforms-stripe-2/api/lib/Stripe/ApiResource.phpon
line 39 and defined in
*/home/admin/domains/
rfahaiti.org/private_html/secure/donate/wp-content/plugins/gravityforms-stripe-2/api/lib/Stripe/InvalidRequestError.php
- on line _5_

_Warning_: Cannot modify header information - headers already sent by
(output started at /home/admin/domains/
rfahaiti.org/private_html/secure/donate/wp-content/plugins/gravityforms-stripe-2/api/lib/Stripe/InvalidRequestError.php:5)
in _/home/admin/domains/
rfahaiti.org/private_html/secure/donate/wp-includes/pluggable.php_ on line *
866*

On Wed, May 23, 2012 at 10:38 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
Hi @pnommensen, I am able to replicate the first warning on my server, but not the second. Even with these warnings, the  webhook from Stripe still goes through successfully.

**Comment by pnommensen** [comment]
Yeah, seems to be working fine though the webhook tests fail and these
errors are present so I was just wondering. Thanks!

On Thu, May 24, 2012 at 12:24 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
@pnommensen Well, it is a problem if your webhook tests are failing. That means that Stripe can't communicate with your server in order to pass event information. My webhook tests are not failing.

**Comment by pnommensen** [comment]
Hmm, Okay my guess is that it's related to the php errors. I will try to
uninstall and re-install - perhaps it's also something on the server that's
blocking it.

On Thu, May 24, 2012 at 12:39 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
@pnommensen Those aren't errors - they're warnings. On a page that will never be directly accessed.

I receive the same warning on my page but my webhooks are _successfully_ testing with Stripe.

**Comment by pnommensen** [comment]
Ah, okay. But still warnings aren't good, right? I'll see if I can get it
to work. Thanks!!

On Thu, May 24, 2012 at 12:46 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by pnommensen** [comment]
(https://rally.org )  

Dear Friends of Rally;
I'm Tom Serres, founder of Rally.org. For nearly a decade, I have believed in the power of online fundraising. I launched Rally.org one year ago as a new way to fundraise and strengthen supporter relationships. I want to thank you - the supporters and causes using Rally - for your generosity and commitment.
This year, we have helped causes large and small reach their fundraising goals, and now we have reached a milestone ourselves.Rally bet on online fundraising and won big. (http://blog.rally.org/rally-raises-7-9-million-online/ ) 
Learn more (http://blog.rally.org/rally-raises-7-9-million-online/ )  about how Rally ate its own online fundraising "dog food." (http://blog.rally.org/rally-raises-7-9-million-online/ ) 
With the support of the co-founder of LinkedIn and an early investor in Twitter, I embarked on an online campaign to raise capital to grow this company. After thousands of emails and meetings, we raised $7.9 million in Series A funding - a historic amount for any company using online funding strategies. I embraced these methods that I believe you can use to reach your goals.
We fundraised our future online, and you can too. (https://rally.org ) I'm excited to use this funding to grow our company and make the Rally platform even better for anyone supporting or raising money for a cause. Never forget that it is the relationships formed with your supporters that ensures the success of your cause.
Thank you.
Now ask yourself, what do you Rally for? (https://rally.org ) 

Tom Serres
CEO and Founder
Rally.org
PS - Learn more about this exciting news by reading my open letter to Rally's community (http://blog.rally.org/rally-raises-7-9-million-online/ )  and help the spread the word about the power of storytelling for change.

Social fundraising for the causes that matter. Connect with Rally
Collect donations online, share your story, reach more people, and make an impact.
(http://facebook.com/Rally )  (http://twitter.com/rally )  (http://blog.rally.org/ ) 
Rally.org (https://rally.org )   

Rally 144 2nd Street, San Francisco, CA, 94105
Unsubscribe from emails about Rally (http://sgemail.rally.org/wf/unsubscribe?upn=diS2Z65q3OkoKPsjgGp5ny8UD58UTCx32ZLzO-2BI-2F2m2pSrh9Ksv-2FashTH5v54skBrtZPsnVq-2BCVYfIXOH8M7h7AAD8OooR0AScnpAzoS4AFbfEvwKwa715vkObMH85xEM1ccMG489QyESteFNngh8-2FSindAWTpZXE-2BIe4J1OMUTcTPsIcQ2iRrPRXcWEFetOWj-2FgBMCdWtxpngRwnJouz4cSn7pbwlanT7syHdNozk4pfP5Zrk82G2lHg4uQULSMbrDMpgUUfqJfbdkf4qby1uVbC69WzkVc9su94GutIF-2BYb32Nslx7t0EcjcBPXdVHmJPxTWgGIdgcx9luZ680QFSk-2FL7-2FRZEXI-2FrNf-2FPxugqPiqxZZACcWnF0RGhsODhOgo-2B5rE8sO1ITNcFhomr7g1uBOiziAORNQJEXHyOKJkgfs3-2BolkdnDZTbA1i4OoZy ) 

 body#nudge { font-family: Verdana, 'Helvetica Neue', Helvetica, Arial, sans-serif !important; font-size: 13px !important; line-height: 1.3 !important; }body#nudge { background-color: #efefef !important; }
