### ISSUE TITLE
2 Forms on Same Site

### ISSUE THREAD

**Issue by pnommensen** [gravityplus/Gravity-Forms-Stripe#13]
Hey! I'm having an issue when I have one recurring form and one single payment form on a single WP site. The subscription one seems to be working fine but I'm getting an Invalid token id: on the other...https://secure.rfahaiti.org/donate/donation/ 

Since I have been able to replicate it on 2 wp installs I'm just going to make a new db and have the single donation be on a separate site for now.

**Comment by naomicbush** [comment]
@pnommensen ok, thanks for reporting :-) I'll take a look.

**Comment by pnommensen** [comment]
Thanks! Perhaps it's just an error on my end...You should make an iPhone
App for Stripe! That could be a big hit....

On Tue, May 29, 2012 at 10:29 AM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
Hi @pnommensen, I checked on this and I was able to successfully use a subscription form and a single product form on one site. The issue you're having sounds like AJAX needs to be enabled on both forms.

Thanks again for reporting - I was able to find and fix another completely unrelated issue during my investigation :-)

**Comment by pnommensen** [comment]
(https://rally.org )  

Dear Friends of Rally;
I'm Tom Serres, founder of Rally.org. For nearly a decade, I have believed in the power of online fundraising. I launched Rally.org one year ago as a new way to fundraise and strengthen supporter relationships. I want to thank you - the supporters and causes using Rally - for your generosity and commitment.
This year, we have helped causes large and small reach their fundraising goals, and now we have reached a milestone ourselves.Rally bet on online fundraising and won big. (http://blog.rally.org/rally-raises-7-9-million-online/ ) 
Learn more (http://blog.rally.org/rally-raises-7-9-million-online/ )  about how Rally ate its own online fundraising "dog food." (http://blog.rally.org/rally-raises-7-9-million-online/ ) 
With the support of the co-founder of LinkedIn and an early investor in Twitter, I embarked on an online campaign to raise capital to grow this company. After thousands of emails and meetings, we raised $7.9 million in Series A funding - a historic amount for any company using online funding strategies. I embraced these methods that I believe you can use to reach your goals.
We fundraised our future online, and you can too. (https://rally.org ) I'm excited to use this funding to grow our company and make the Rally platform even better for anyone supporting or raising money for a cause. Never forget that it is the relationships formed with your supporters that ensures the success of your cause.
Thank you.
Now ask yourself, what do you Rally for? (https://rally.org ) 

Tom Serres
CEO and Founder
Rally.org
PS - Learn more about this exciting news by reading my open letter to Rally's community (http://blog.rally.org/rally-raises-7-9-million-online/ )  and help the spread the word about the power of storytelling for change.

Social fundraising for the causes that matter. Connect with Rally
Collect donations online, share your story, reach more people, and make an impact.
(http://facebook.com/Rally )  (http://twitter.com/rally )  (http://blog.rally.org/ ) 
Rally.org (https://rally.org )   

Rally 144 2nd Street, San Francisco, CA, 94105
Unsubscribe from emails about Rally (http://sgemail.rally.org/wf/unsubscribe?upn=diS2Z65q3OkoKPsjgGp5ny8UD58UTCx32ZLzO-2BI-2F2m2Wcp0wTHRs0LKx9jo0QanFDz5pckJEGfyiJpmSTtcKpmlV-2FyPfn9ZgbvaA5Krsp60ssmwx8Brh1pzUknph1r4SYfdQHuqcaSX-2BtGbuuMhfwPE4E-2FTxga-2FillEFspzCHJR6hdwwfoGsJzDyNjOr1n7B2VHvlpgd43lIzZgo-2B2q4MQjK-2F4OWj05JKmLpCJ-2Fshfp4azvizIs6fsUW-2FC5Odo2k-2FkwZdUlqDEonuZ8GlaRizZqaADFEi0sZspwabZS-2Bi5j401LkMFWJ5RF2ZKr1yECfxuVR6JVMfi5NdIG5RLDFiNCxsQwYlverPq7UnV42uMGzi8qzkE1ILd3ue-2BI4Ei7-2B55KwOTk9VcWT1wyyhB9uxNiknpTuv-2FqTvy9n3nAaOUcRZXibhNKYsl-2FIyIT3G53o ) 

 body#nudge { font-family: Verdana, 'Helvetica Neue', Helvetica, Arial, sans-serif !important; font-size: 13px !important; line-height: 1.3 !important; }body#nudge { background-color: #efefef !important; }
