### ISSUE TITLE
Form Not Submitting

### ISSUE THREAD

**Issue by aaronaiken** [gravityplus/Gravity-Forms-Stripe#15]
Hello,

I am running 0.2 Beta of Gravity Forms Stripe Add-on and 1.6.4.5.4 of Gravity Forms using a developer license. 

My problem is this: upon filling out the form information and clicking 'submit' the "spinner" just spins and the form is never actually submitted. 

I have setup my form and Stripe subscription product following all of the steps included in the readme.md instructions included with the Stripe Add-on plugin. I have also tested this with a different theme, and by deactivated and reactivated one by one each of my plug-ins. I am running this on a multisite install, but have seen in another issue that was resolved that multisite, while not supported, does work. 

I've spent several hours now testing and tweaking and would appreciate any tips/tricks/suggestions to get this working.

Form is located here: http://aikenwebsolutions.com/monthly

Thanks in advance for your time,
- Aaron Aiken

**Comment by naomicbush** [comment]
Hi @aaronaiken - do you have the plugin network-activated or just activated on a single site? If the former, try activating it using the latter method and report back.

**Comment by aaronaiken** [comment]
Naomi, 

...you have those days, right? Where you are digging into what you think to be the issue when in-fact the issue is lack of caffeine or lack of not taking enough breaks? The problem, as I'm sure you may have assumed, was not your plug-in, but was me. Turns out that through all of my testing and tweaking I never confirmed that the Stripe plugin was in test mode... :-/

Having noticed that I put both Stripe and the Stripe plugin in test mode and the form submitted fine, payment made it to Stripe, etc. No problem. 

Sorry to raise an issue when there was none.

Thanks for responding.

Aaron Aiken

**Comment by naomicbush** [comment]
@aaronaiken cool :-)
