### ISSUE TITLE
Invalid Token in GF 1.6.4.5.4

### ISSUE THREAD

**Issue by jamesvandyke** [gravityplus/Gravity-Forms-Stripe#16]
When using either version 0.1.3 or 0.2 with Gravity Forms version 1.6.4.5.4, upon submission an Invalid Token error is returned from Stripe.

In my Stripe logs I see the following information 

"400 ERR POST/v1/charges"

Request body:

``` javascript
{
  "description": "james@jamesvandyke.com: (1)\tDonation\t\tx\t$5",
  "currency": "usd",
  "amount": "500",
  "card": ""
}
```

Response body:

``` javascript
{
  "error": {
    "type": "invalid_request_error",
    "message": "Invalid token id: "
  }
}
```

**Comment by naomicbush** [comment]
This issue has been fixed in an updated version of the plugin that's been made available to those that have donated. I plan on making it available here in another week or two.

**Comment by naomicbush** [comment]
Hi @eddiemachado - do you need the recurring payments/subscription feature?  You can donate here: https://naomicbush.com

**Comment by naomicbush** [comment]
@eddiemachado It is. I also have another version for those that wanted the other parts of the Stripe API implemented, like recurring payments and coupons. 

As far as future GF updates, I plan to take advantage of their usual beta periods to fix as many compatibility issues as I can before the new GF release.
