### ISSUE TITLE
Multiple Currencies

### ISSUE THREAD

**Issue by Melisssa** [gravityplus/Gravity-Forms-Stripe#18]
Is it possible to use this addon with multiple currencies on one form?  Thanks

**Comment by Melisssa** [comment]
Ah!  Thanks Naomi.  If they only do USD, then that makes sense.  Thank you for the quick response and looking into that for me.

Just wanted to mention, on the FAQ page, https://stripe.com/help/faq - it does mention any currency, but it's just converted to USD.  Would that be supported in this addon?

**Comment by naomicbush** [comment]
@Melisssa here's my final answer: 
- Stripe allows for multiple currencies in this way: a customer can pay with a non-US credit card and their bank will automatically convert their currency to the USD that Stripe needs. 

So you **can** accept multiple currencies with this add-on. There's no need to do anything extra or enable anything extra in the add-on. It's all handled by Stripe and the customer's bank. As long as they pay with the Visa, Mastercard, and other supported card types, the payment will be processed correctly across currencies.
