### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by Melisssa** [gravityplus/Gravity-Forms-Stripe#19]
Hello,

I've installed the plugin and went to Stripe Account Information to add in the API keys and after I save the settings, I get a little red icon and message "Invalid API Key. Please try again".   I went to stripe and rolled a new key and tried those and it still didn't work.  I then went to another stripe account and tried those API keys with the same result.

Thank you for any assistance you can provide for this issue.

**Comment by naomicbush** [comment]
Already addressed in the latest fix.
