### ISSUE TITLE
Spinning "working" indicator issues

### ISSUE THREAD

**Issue by admodiggity** [gravityplus/Gravity-Forms-Stripe#2]
If there is an error in one of the form fields, the spinning "working" indicator appears next to the SUBMIT button and never stops spinning.

The SUBMIT button is not disabled, and if it is pressed again another spinning indicator will appear.

I pressed it four times in the attached screengrab.

![Broken spinning indicator](http://www.adamrichardson.com/lotsa-working-indicators.png)

**Comment by naomicbush** [comment]
Grab version 0.1.2.

commit [f2772af025](https://github.com/naomicbush/Gravity-Forms-Stripe/commit/f2772af0253c1363bddddd62a38da009deb965be) `Fix error handling`
