### ISSUE TITLE
Newer Stripe Accounts Problem

### ISSUE THREAD

**Issue by leoken** [gravityplus/Gravity-Forms-Stripe#21]
I've run into a problem with the plugin and I think I've narrowed it down based on what Stripe support has told me. 

I have the plugin working on a few web sites I'm running. It works perfectly.

But I have a site I just launched and it has a brand new Stripe account and the plugin will not work. 
I actually tried switching API keys from the newer Stripe account to my older one and it works fine. So, that means it's got something to do with NEW Stripe accounts. 

The reason it's not working is because (this is directly from Stripe support):

"It looks like you're passing the "currency" attribute when creating tokens using Stripe.js. We deprecated this attribute a while ago, but we only show that error for newer Stripe accounts. To fix this problem, you'll need to remove this attribute from your createToken call."

Has anyone else run into this same problem?

**Comment by codearachnid** [comment]
It looks like I'm running into the same issue on a stripe account that was created about 1.5 months ago

**Comment by naomicbush** [comment]
known issue - fixed in latest update
