### ISSUE TITLE
No Redirect from stripe

### ISSUE THREAD

**Issue by imashukla** [gravityplus/Gravity-Forms-Stripe#24]
Hello Naomi,
I am trying to make set up for stripe payment .Right now i am working
in testing mode and i have set up all keys and create a webhook url on stripe account we have also mention redirect url in account on tsting mode but its not going to redirect on mention server or localhost after login into stripe can you please help us

**Comment by pnommensen** [comment]
Official support from the plugin developer can be purchased here: https://gravityplus.pro/. 

However, I can help and may find what's going on. Can you send the URL? I doubt this is an issue with the plugin but rather a mis configuration of some type.
