### ISSUE TITLE
Error with on multipage form

### ISSUE THREAD

**Issue by jupitercow** [gravityplus/Gravity-Forms-Stripe#25]
I have a multipage form, 3 pages:
1. name, email, phone, password, and a few other pieces of meta data.
2. billing address, products, radio to choose subscription, and coupon
3. html field that shows summary info and credit card.

Everything goes well, but when the third page is submitted, I get this error:

> Fatal error: Call to a member function delete() on a non-object in /[path to directory]/carss/wp-content/plugins/gravityforms-stripe-more/more-stripe.php on line 713

Link to register form on our test site using test stripe account: http://carss.staging.wpengine.com/register/

Also, stripe log is showing 200 status.

**Comment by jupitercow** [comment]
It might just be me having this problem, but it seems like there might be an issue if you don't have a setup fee?

I changed the line to make sure a setup fee exists first (I also checked for the 'delete' method, but that probably isn't needed). Tthings seem to working correctly now:

from:

> $setup_fee->delete();

to:

> if ( is_object($setup_fee) && method_exists($setup_fee, 'delete') ) $setup_fee->delete();

**Comment by naomicbush** [comment]
Support for More Stripe is here:

https://gravityplus.pro
