### ISSUE TITLE
"Empty string for 'card'"

### ISSUE THREAD

**Issue by georgemandis** [gravityplus/Gravity-Forms-Stripe#26]
I keep getting this validation error when I attempt to submit a form that includes the Stripe credit card field:

```
You passed an empty string for 'card'. We assume empty values are an attempt to 
unset a parameter; however 'card' cannot be unset. You should remove 'card' from 
your request or supply a non-empty value
```

I've been using Stripe in test mode and 4242424242424242 as the card #. 

I'm using the latest version of Gravity Forms (1.7.11) and this version of the Gravity Forms Stripe plugin...

Has anyone else experienced this issue?

**Comment by naomicbush** [comment]
Here are the troubleshooting steps:

http://wordpress.org/plugins/gravity-forms-stripe/faq/
