### ISSUE TITLE
$plugin isn't what you expect when network activating with individual plugins activated for a site

### ISSUE THREAD

**Issue by sc0ttkclark** [gravityplus/Gravity-Forms-Stripe#27]
``` php
if ( isset( $plugin ) ) {
    $gfp_stripe_file = $plugin;
}
else if ( isset( $mu_plugin ) ) {
    $gfp_stripe_file = $mu_plugin;
}
else if ( isset( $network_plugin ) ) {
    $gfp_stripe_file = $network_plugin;
}
```

This line is causing me trouble because $network_plugin is set correctly to this plugin's location, but $plugin contains another previously loaded plugin.

**Comment by naomicbush** [comment]
Thanks for reporting. It's added to my list of things to look into — no guarantees on time, though.

**Comment by naomicbush** [comment]
This is fixed in the next version. Thanks again :-)
