### ISSUE TITLE
Initial gform_currencies throwing errors

### ISSUE THREAD

**Issue by sc0ttkclark** [gravityplus/Gravity-Forms-Stripe#28]
Just network activated the plugin, but getting these errors because $currencies_supported isn't set (no stripe key set, no currency set).

```
Warning: array_flip() expects parameter 1 to be array, null given in /nas/wp/www/staging/xxxxxx/wp-content/plugins/gravity-forms-stripe/includes/GFP/Stripe/class-gfp-stripe.php on line 643

Warning: array_intersect_key() [function.array-intersect-key]: Argument #2 is not an array in /nas/wp/www/staging/xxxxxx/wp-content/plugins/gravity-forms-stripe/includes/GFP/Stripe/class-gfp-stripe.php on line 643
```

**Comment by naomicbush** [comment]
Thanks for reporting. I'll see if this is a Multisite network activation issue since it doesn't occur on single sites or when individually activated on a Multisite install — no guarantees on time, though.
