### ISSUE TITLE
Accepting Multiple Currencies

### ISSUE THREAD

**Issue by galsh** [gravityplus/Gravity-Forms-Stripe#32]
Hi Naomi,

How did your plugin know to automatically provide a Euro symbol instead of a Dollar symbol? Also is it possible to allow users to select and then pay in their local currencies? I know stripe allow it and I believe they charge a 2% fee on top of market rates. 

Thanks and great plugin by the way.

**Comment by galsh** [comment]
Apologies Naomi, I'm just after seeing where the currency setting is. Is it possible to change this via a drop down in for form?

**Comment by naomicbush** [comment]
Hi :-) You can do this in the premium extension, found at gravityplus.pro
