### ISSUE TITLE
Coupons Not Showing for Products and Services

### ISSUE THREAD

**Issue by jonahcoyote** [gravityplus/Gravity-Forms-Stripe#33]
Hi there,

The coupon option does not show for the Products and Services Transaction type, only Subscriptions. Is this a current limitation or just an oversight? Seems like if the former, you should make it more clear in the plugin documentation.

Thanks,
Jonah

**Comment by pnommensen** [comment]
Are you using the paid extension? https://gravityplus.pro

**Comment by jonahcoyote** [comment]
Yep. Naomi just replied to my support request and apparently coupons are not available for regular one-time payments...

**Comment by pnommensen** [comment]
Yeah. You can just apply them to invoices or subscriptions. So your app would need to calculate the reduced charge amount before sending to Stripe. 

Check out the "Adding the Coupon to One Time Payments" section here http://pippinsplugins.com/stripe-integration-part-5-accepting-discount-codes/. 

I think it would be a useful feature to add to either the free plugin or premium extension. One could define certain one-time payment coupons in the WordPress dashboard. Then have a field in the payments form asking for coupon and if it matches an existing coupon from the WP Database then change the charge amount on the fly. What do you think? @naomicbush @jonahcoyote

**Comment by jonahcoyote** [comment]
I found this and it works perfectly, so no reason to reinvent the wheel: http://www.gravityforms.com/add-ons/coupons/

It'd be a good idea to update the documentation and description of the plugin to make clear coupons only work with Subscriptions and suggest using the native Gforms plugin to accept coupons for one time products/payment.

Thanks!

**Comment by pnommensen** [comment]
Cool, didn't know that existed :)

**Comment by naomicbush** [comment]
Thanks. This issue was unrelated to this repo, but it was added to the premium extension :-)
