### ISSUE TITLE
check to make sure its a stripe enabled form

### ISSUE THREAD

**Issue by andrewscofield** [gravityplus/Gravity-Forms-Stripe#35]
It would be nice if you could make this function check if the form being modified is actually setup to process through stripe:

https://github.com/naomicbush/Gravity-Forms-Stripe/blob/master/includes/GFP/Stripe/class-gfp-stripe.php#L3922

I just ran into an issue where I had to use paypal on a site that I normally use stripe and this caused it to save the full credit card number to my database

**Comment by naomicbush** [comment]
Thanks! That's actually already been handled in the next release about to be pushed. If you email me (gravityplus.pro), I can send it to you.
