### ISSUE TITLE
Forgetting to fill in CVC clears out all credit card fields

### ISSUE THREAD

**Issue by admodiggity** [gravityplus/Gravity-Forms-Stripe#5]
Common scenario:

I enter in my credit card name, number, and expiration but don't fill in the CVC. (maybe I'm not even sure what a CVC is, some banks call it a "security code")

If I don't enter a CVC, the plugin reports the correct error code ("invalid CVC") but clears out the name and credit card number.  It would be great if those fields would persist like all of the other fields, since it's a hassle to enter in a 16 digit number.

**Comment by naomicbush** [comment]
Unfortunately the plugin can't fill the credit card # back in because it cannot be saved/persist at all due to PCI regulations.
