### ISSUE TITLE
Payment will not process if GravityForms AJAX is not enabled

### ISSUE THREAD

**Issue by admodiggity** [gravityplus/Gravity-Forms-Stripe#6]
If you do not check the **Enable AJAX** checkbox when inserting a GravityForm into a page, the form will always generate an **Invalid token id** error.  

Also, none of the fields are error checked.  If you leave all credit card fields empty the plugin generates the same **Invalid token id** error, but does not return any error checking telling you to populate the empty fields.

**Comment by naomicbush** [comment]
Hi Adam, yes this is correct. Right now, I'm hooking into the Gravity Forms AJAX to do all the Stripe stuff.

I'll add getting it to work without AJAX to the list of enhancements but don't see this as a high priority over subscriptions. Unless you'd like to convince me otherwise :-)

**Comment by michelangelo33** [comment]
Not sure if this is the same, but with AJAX enabled, Internet Explorer 8 will not redirect when clicking the submit button.

The data goes through, but remains on the same page. Clicking submit over and over submits the info over and over.

In Safari and Chrome, works fine. In IE without AJAX, it works fine, except for not being able to enter cc info (invalid token).

**Comment by naomicbush** [comment]
Thanks for reporting, @michelangelo33 - the IE bug has been moved to issue #8
