### ISSUE TITLE
Hangs on IE8

### ISSUE THREAD

**Issue by admodiggity** [gravityplus/Gravity-Forms-Stripe#8]
Moving this to a new issue.

After pressing the submit button on IE8, the AJAX "wait" cursor spins indefinitely.

**Comment by naomicbush** [comment]
Thanks @admodiggity. From @michelangelo33's report, 

> The data goes through, but remains on the same page. Clicking submit over and over submits the info over and over.

which leads me to believe this is a JavaScript problem. I'm always open to fixes :-)

**Comment by naomicbush** [comment]
Hi @admodiggity, I tested this w/ IE8 on Windows XP and could not replicate the issue.

![Gravity Forms Stripe IE8 successful transaction](http://naomicbush.com/files/Stripe-IE8-single-payment.png)
