### ISSUE TITLE
Feature Request: Add to Stripe Customers List

### ISSUE THREAD

**Issue by pnommensen** [gravityplus/Gravity-Forms-Stripe#9]
Hi,

The development of this plugin is looking really great. I was wondering if it's possible for the plugin to create a customer in addition to logging the payment at https://manage.stripe.com/. This would be a very neat feature because it would include address and so forth. I know the plugin has settings for address, et cetera, but I don't see that data recorded anywhere.

Many thanks.

**Comment by naomicbush** [comment]
@pnommensen Currently that data is stored in Gravity Forms, on the entry detail screen, if you include an address field on your form.  

Sounds reasonable enough to create a customer in Stripe and that's exactly how subscriptions work, but for one-time payments all of the storing & tracking of customers would have to be done in WP and that seems to me to be a lot of overhead for one-time payments as this is not a "shopping cart." I'm open, though, if you have a different view.

**Comment by pnommensen** [comment]
OK, yes. Would it be possible to have the a form submission send the
customer info to stripe to create a customer profile @
https://manage.stripe.com/#customers ?

On Tue, May 1, 2012 at 4:40 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
@pnommensen See my updated comment above.

**Comment by pnommensen** [comment]
@naomicbush I understand what you're saying :-). My only argument would be for nonprofit organizations: it's nice to have entries for all the single donation donors in one place - stripe. I'm brand new to Stripe so I'm not yet 100% of how it works...though we will be using your plugin for all our donations once it's ready! thanks again.

**Comment by naomicbush** [comment]
@pnommensen I actually created the plugin for a nonprofit :-) Honestly, IMO, the Stripe dashboard leaves much to be desired as the single point of reference for meaningful reporting. But let's have a Skype chat later on today or tomorrow - I'll email you.

**Comment by pnommensen** [comment]
Yes..I actually agree now that you say that. We are used to having excel
spreadsheets and that's about it! I think the problem is that we don't
really know what we want or need. As long as it handles the recurring
payments well this will work perfectly.

On Tue, May 1, 2012 at 5:02 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
@pnommensen I took a look at this again & can see how it would make sense to have this information listed in the Stripe dashboard 'Customers' section, even if there are duplicates (as there will be). I'm considering implementing this but am admittedly a bit put off by how may API calls it will take. Right now, there's only one two, but this feature will add at least 2 more :-(

**Comment by pnommensen** [comment]
Oh, okay - that doesn't sound good? I'm not really familiar with how this
all works just yet. It's not a huge deal as we can just have that info
emailed to us (via gravity forms) and input in our excel sheet. Recurring
donations are the most important for us :-).

On Wed, May 2, 2012 at 5:47 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by naomicbush** [comment]
This has been addressed in v0.2 now available for testing.

**Comment by pnommensen** [comment]
Yes, I got your email this morning!

On Tue, May 8, 2012 at 12:41 PM, Naomi C. Bush <
reply@reply.github.com

**Comment by pnommensen** [comment]
(https://rally.org )  

Dear Friends of Rally;
I'm Tom Serres, founder of Rally.org. For nearly a decade, I have believed in the power of online fundraising. I launched Rally.org one year ago as a new way to fundraise and strengthen supporter relationships. I want to thank you - the supporters and causes using Rally - for your generosity and commitment.
This year, we have helped causes large and small reach their fundraising goals, and now we have reached a milestone ourselves.Rally bet on online fundraising and won big. (http://blog.rally.org/rally-raises-7-9-million-online/ ) 
Learn more (http://blog.rally.org/rally-raises-7-9-million-online/ )  about how Rally ate its own online fundraising "dog food." (http://blog.rally.org/rally-raises-7-9-million-online/ ) 
With the support of the co-founder of LinkedIn and an early investor in Twitter, I embarked on an online campaign to raise capital to grow this company. After thousands of emails and meetings, we raised $7.9 million in Series A funding - a historic amount for any company using online funding strategies. I embraced these methods that I believe you can use to reach your goals.
We fundraised our future online, and you can too. (https://rally.org ) I'm excited to use this funding to grow our company and make the Rally platform even better for anyone supporting or raising money for a cause. Never forget that it is the relationships formed with your supporters that ensures the success of your cause.
Thank you.
Now ask yourself, what do you Rally for? (https://rally.org ) 

Tom Serres
CEO and Founder
Rally.org
PS - Learn more about this exciting news by reading my open letter to Rally's community (http://blog.rally.org/rally-raises-7-9-million-online/ )  and help the spread the word about the power of storytelling for change.

Social fundraising for the causes that matter. Connect with Rally
Collect donations online, share your story, reach more people, and make an impact.
(http://facebook.com/Rally )  (http://twitter.com/rally )  (http://blog.rally.org/ ) 
Rally.org (https://rally.org )   

Rally 144 2nd Street, San Francisco, CA, 94105
Unsubscribe from emails about Rally (http://sgemail.rally.org/wf/unsubscribe?upn=diS2Z65q3OkoKPsjgGp5n75WRNaX8hVh826jNpI2Qz-2BtnumiTGXU9ShRo0hSKvg0yT2ngp03Y5hIcI7B-2FqR1AKBZipoYLSxfM5nyJqbCEERvvFWZ2rmfvdJeCB1jZZ4hxTOK2Y0JztijFXHyVbqxpeIjVWfa-2BfdIuboo2XhSKnlRonw-2BMTfW-2BCQkYYn5lFCavrQ6f4d9lXEIkWEMdOvB03MWSVQ0jXA0BsQxGJGM7tsSFxmL5WJdQE2OXvbKHylZRGVEPkMA1O2aAngrqPR4cKnMcyCGreGn1R4kPju-2BUgl5okq8yUSAcoiu-2Bcs6B6m0VNXRfQbhbph-2Bxy58TagUiMfVPxxIerIy47SZf5jTbDZaW1mk07zWJXg2Nvvysjv-2BDc85HqZbCvVOaufXkFSpgIFcrBkoLrR83ZXUr5Rb7xXsMTql7DaH-2BZQKsfYKGrQU ) 

 body#nudge { font-family: Verdana, 'Helvetica Neue', Helvetica, Arial, sans-serif !important; font-size: 13px !important; line-height: 1.3 !important; }body#nudge { background-color: #efefef !important; }
